[build]
  # Use the latest Ubuntu Jammy (22.04) image instead of Focal (20.04)
  environment = { NODE_VERSION = "20" }
  
  # Build settings
  publish = "build"
  command = "npm run build"

[build.environment]
  # Specify the build image - using Jammy instead of deprecated Focal
  NETLIFY_BUILD_IMAGE = "ubuntu-22.04"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"