[build]
  # Build settings
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Use Node.js 20
  environment = { NODE_VERSION = "20.13.1" }

[build.environment]
  # Force platform for sharp
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  npm_config_arch = "x64"
  npm_config_platform = "linux"
  # Use newer Ubuntu image
  NETLIFY_IMAGE_TAG = "v4.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"